# Generated by Django 3.2.3 

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joyas',
            fields=[
                ('IdJoyas', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de joyas')),
                ('TipoJoya', models.CharField(max_length=30, verbose_name='TipoJoya')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('RutCliente', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='RutCliente')),
                ('Joyas', models.CharField(max_length=25, verbose_name='Joyas')),
                ('Dirección', models.CharField(max_length=100, verbose_name='Dirección')),
            ],
        ),
    ]
